tabdown/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tablatures.urls')),
]

tablatures/urls.py
from django.urls import path

from .views import SongListView, AboutPageView, SongDetailView, SongCreateView, SongUpdateView, SongDeleteView, \
    generate_gp5

urlpatterns = [
    path('about/', AboutPageView.as_view(), name='about'),
    path('song/new/', SongCreateView.as_view(), name='song_new'),
    path('song/<int:pk>/delete/', SongDeleteView.as_view(), name='song_delete'),
    path('song/<int:pk>/edit/', SongUpdateView.as_view(), name='song_edit'),
    path('song/<int:pk>/guitarpro/', generate_gp5, name="song_gp5"),
    path('song/<int:pk>/', SongDetailView.as_view(), name="song_detail"),
    path('', SongListView.as_view(), name='home'),
]

tablatures/models.py
from django.db import models
from django.urls import reverse
from multiselectfield import MultiSelectField


class Artist(models.Model):
    name = models.CharField(max_length=50)
    bass_player = models.CharField(max_length=50)

    def __str__(self):
        return self.name + " (" + self.bass_player + ")"

    class Meta:
        ordering = ['name']


class Song(models.Model):
    name = models.CharField(max_length=50)
    artist = models.ForeignKey('Artist', on_delete=models.PROTECT)
    tablature_source = models.TextField(blank=True, default='')

    def __str__(self):
        return self.name

    @property
    def number_of_measures(self):
        return len(self.tablature_source.splitlines())

    @property
    def artist_name(self):
        return self.artist.name

    def get_absolute_url(self):
        return reverse('song_detail', args=[str(self.id)])

tablatures/views.py
from django.views.generic import ListView, TemplateView, DetailView, CreateView, UpdateView, DeleteView
from .models import Song
from django.urls import reverse_lazy
from django.http import FileResponse
from .song_exporter import export_song
import io


class SongListView(ListView):
    model = Song
    template_name = 'home.html'
    context_object_name = 'all_songs_list'
    ordering = ['artist', 'name']


class SongDetailView(DetailView):
    model = Song
    template_name = 'song_detail.html'


class SongCreateView(CreateView):
    model = Song
    template_name = 'song_new.html'
    fields = ['name', 'artist', 'tablature_source']
    initial = {'tablature_source': "tuning(E2,A2,D3,G3) tempo(q,120) marker(Intro) -w"}


class SongUpdateView(UpdateView):
    model = Song
    template_name = 'song_edit.html'
    fields = ['name', 'artist', 'tablature_source']


class SongDeleteView(DeleteView):
    model = Song
    template_name = 'song_delete.html'
    success_url = reverse_lazy('home')


class AboutPageView(TemplateView):
    template_name = 'about.html'


def generate_gp5(request, pk):
    song = Song.objects.get(id=pk)
    buffer = io.BytesIO()
    export_song(song, buffer)
    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename=song.name + '.gp5')

templates/about.html
{%  extends 'base.html' %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/base.html
{% load static %}

<html>
<head>
    <title>TabDown</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <!-- Required styles for MDC Web -->
    <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>

    <script src="https://unpkg.com/lodash"></script>
    <script src="https://unpkg.com/codeflask/build/codeflask.min.js"></script>
    <script src="https://unpkg.com/vexflow/releases/vexflow-debug.js"></script>
    <script src="{% static 'js/tabdown.js' %}"></script>
    <script src="{% static 'js/tabdown_parser_actions.js' %}"></script>
</head>
<header>
    <div class="nav-left">
        <a href="{% url 'home' %}">Home</a> | <a href="{% url 'about' %}">About</a>
    </div>
    <div class="nav-right>">
        <a href="{% url 'song_new' %}">+ New Song</a>
    </div>
</header>
<body>
<div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
        {% block content %}
        {% endblock content %}
    </div>
</div>

<!-- Required MDC Web JavaScript library -->
<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>

<!-- Instantiate single textfield component rendered in the document -->
<script>
    // mdc.textField.MDCTextField.attachTo(document.querySelector('.mdc-text-field'));
</script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="mdc-layout-grid__cell--span-12">

    <h1>Tablatures</h1>
    <ul>
        {% for song in all_songs_list %}
            <div class="song-entry">
                <li><a href="{% url 'song_detail' song.pk %}">{{ song.name }} ( {{ song.number_of_measures }} measures) - {{ song.artist.name }}</a></li>
            </div>
        {% endfor %}
    </ul>
    </div>
{% endblock content %}

templates/song_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Song</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ song.name }}"</p>
        <input type="submit" value="Confirm"/>
    </form>

{% endblock content %}

templates/song_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="mdc-layout-grid__cell--span-12">
        <p><a href="{%  url 'song_edit' song.pk %}">+ Edit Song</a>
        <a href="{%  url 'song_gp5' song.pk %}">+ Download GP5</a>
        <a href="{%  url 'song_delete' song.pk %}">+ Delete Song</a></p>
    </div>

    <div class="mdc-layout-grid__cell--span-12">
        <div class="song-entry">
            <h2>{{ song.name }}</h2>
            <p>{{ song.artist.name }}</p>
            <p>{{ song.artist.bass_player }}</p>
            <input type="hidden" id="id_tablature_source" value="{{ song.tablature_source }}">
        </div>
    </div>

    <div class="mdc-layout-grid__cell--span-12">
        <div id="tablature_wrapper">
            <div id="tablature">
            </div>
        </div>
    </div>
    <div class="mdc-layout-grid__cell--span-12">
        <div id="tuning"></div>
    </div>
    <div class="mdc-layout-grid__cell--span-12">
        <div id="editor" class="readonly"></div>
    </div>


    <script src="{% static 'js/main.js' %}"></script>

{% endblock content %}

templates/song_edit.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="mdc-layout-grid__cell--span-12">
        <h1>Edit Song</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update"/>
            <input type="button" value="Refresh" onclick="update();">
        </form>
    </div>

    <div class="mdc-layout-grid__cell--span-12">
        <div id="tablature_wrapper">
            <div id="tablature">
            </div>
        </div>
    </div>
    <div class="mdc-layout-grid__cell--span-12">
        <div id="tuning"></div>
    </div>
    <div class="mdc-layout-grid__cell--span-12">
        <div id="editor"></div>
    </div>
    <div class="mdc-layout-grid__cell--span-12">
        <pre id="error"></pre>
    </div>


    <script src="{% static 'js/main.js' %}"></script>

{% endblock content %}

templates/song_new.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h1>New Song</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
    <script src="{% static 'js/main.js' %}"></script>

{% endblock content %}